#!/bin/sh

usage()
{
    echo "usage: run_tests [-h]"
}

NP=1
while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

repo=$(dirname $(dirname $(realpath $0) ) )

echo $repo

pytest-3 --disable-warnings $repo/poisson/1d/fenics/poisson.py

tfsimulationharness --test $repo/poisson/1d/TF/poisson.shml

pytest-3 --disable-warnings $repo/poisson/2d/fenics/poisson.py

tfsimulationharness --test $repo/poisson/2d/TF/poisson.shml

tfsimulationharness --parameters nelements 32 --test $repo/blankenbach/1a-c/blankenbach.shml

tfsimulationharness --parameters nelements 32 --test $repo/blankenbach/2a/blankenbach.shml

tfsimulationharness --parameters nelements 20 nelements 40 nelements 80 --test $repo/cornerflow/cornerflow.shml

tfsimulationharness --parameters minres 2.0 --test $repo/subduction_benchmark/case1/subduction_steadystate_linpicard_p2p1p2.shml

tfsimulationharness --parameters minres 2.0 --test $repo/subduction_benchmark/case2/subduction_steadystate_linpicard_p2p1p2.shml

