#!/bin/sh

usage()
{
    echo "usage: run_tests [-h]"
}

NP=1
while [ "$1" != "" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

repo=$(dirname $(dirname $(realpath $0) ) )

echo $repo

pytest-3 --disable-warnings $repo/1d_poisson/fenics/poisson.py

tfsimulationharness --test $repo/1d_poisson/tf/poisson.shml

tfsimulationharness --parameters ncells 32 --test $repo/blankenbach/1a-c/blankenbach.shml

tfsimulationharness --parameters ncells 32 --test $repo/blankenbach/2a/blankenbach.shml

tfsimulationharness --parameters ncells 20 ncells 40 ncells 80 --test $repo/cornerflow/cornerflow.shml

tfsimulationharness --parameters resscale 2.0 --test $repo/subduction_benchmark/case1/subduction_steadystate_linpicard_p2p1p2.shml

tfsimulationharness --parameters resscale 2.0 --test $repo/subduction_benchmark/case2/subduction_steadystate_linpicard_p2p1p2.shml

